import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import "./globals.css";

export const metadata: Metadata = {
  title: "Mapache Studio — Estudio de grabación & arte",
  description: "Donde el sonido toma forma y el arte encuentra su voz. Producción musical, audiovisual y diseño en un solo lugar.",
  icons: {
    icon: '/mapache-logo.png',
    apple: '/mapache-logo.png',
  },
>>>>>>> dev
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
=======
    <html lang="es">
>>>>>>> dev
      <body>{children}</body>
    </html>
  );
}
